openapi: 3.1.0
info:
  title: Traductor Excel
  version: 1.0.0
servers:
  - url: https://excel-gpt-api.onrender.com

paths:
  /extraer_texto:
    post:
      operationId: extraerTextoExcel
      summary: Extrae el texto de un archivo Excel
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema
